name: CI

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci

      - run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review

      - uses: reviewdog/action-markdownlint@v0
        with:
          reporter: github-pr-review

      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
